aliases:
  - &git-checkout
    name: Checkout
    command: |
      mkdir -p ~/.ssh && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      git clone --depth 1 -b $CIRCLE_BRANCH $CIRCLE_REPOSITORY_URL ./ && \
      git checkout $CIRCLE_SHA1
  - &environment
      JVM_OPTS: -Xmx3200m
      TERM: dumb
  - &docker-openjdk-worker
      - image: circleci/openjdk:8-jdk
  - &restore-cache
    keys:
    - v1-dependencies-{{ checksum "build.gradle" }}
    - v1-dependencies-
  - &save-cache
    paths:
       - ~/.gradle
    key: v1-dependencies-{{ checksum "build.gradle" }}
  - &gradle-deps
    name: Setup Gradle Dependencies
    command: ./gradlew dependencies
  - &gradle-test
    name: Gradle Test
    command: ./gradlew test
  - &make-executable
    name: Make Jar Executable
    command: ./gradlew bootJar
  - &setup-remote-docker
    setup_remote_docker:
      docker_layer_caching: false
  - &update-submodules
    name: Update submodules
    command: |
      git submodule init && \
      git submodule update
  - &containerize-push
    name: Containerize and Push
    command: |
      echo $DOCKER_PASSWORD > docker_passwd && \
      docker login -u $DOCKER_USERNAME --password-stdin < docker_passwd && rm docker_passwd && \
      docker build -t aeternas/swadeshness-spring:$CIRCLE_BRANCH . && \
      docker push aeternas/swadeshness-spring:$CIRCLE_BRANCH
      if [[ $CIRCLE_BRANCH == "master" ]]; then
        docker tag aeternas/swadeshness-spring:master aeternas/swadeshness-spring:latest && \
        docker push aeternas/swadeshness-spring:latest
      fi
version: 2.1
jobs:
  build:
    docker: *docker-openjdk-worker
    working_directory: ~/repo
    environment: *environment
    steps:
      - run: *git-checkout
      - run: *update-submodules
      - restore_cache: *restore-cache
      - run: *gradle-deps
      - save_cache: *save-cache
      - run: *gradle-test
      - run: *make-executable
      - *setup-remote-docker
      - deploy: *containerize-push
workflows:
  version: 2.1
  build-containerize-push:
    jobs:
      - build
