aliases:
  - &restore-cache
    keys:
    - v1-dependencies-{{ checksum "build.gradle" }}
    - v1-dependencies-
  - &save-cache
    paths:
       - ~/.gradle
    key: v1-dependencies-{{ checksum "build.gradle" }}
  - &test
    name: Gradle Test
    command: ./gradlew test
  - &make_executable
    name: Make Jar Executable
    command: ./gradlew bootJar
  - &setup_remote_docker
    setup_remote_docker:
      docker_layer_caching: true
  - &containerize_push
    name: Containerize and Push
    command: |
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && \
      docker build -t aeternas/swadeshness-spring:$CIRCLE_BRANCH . && \
      docker push aeternas/swadeshness-spring:$CIRCLE_BRANCH
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: gradle dependencies
      - save_cache: *save-cache
      - run: *test
      - run: *make_executable
      - *setup_remote_docker
      - deploy: *containerize_push
