aliases:
  - &restore-cache
    keys:
    - v1-dependencies-{{ checksum "build.gradle" }}
    - v1-dependencies-
  - &save-cache
    paths:
       - ~/.gradle
    key: v1-dependencies-{{ checksum "build.gradle" }}
  - &gradle-deps
    name: Setup Gradle Dependencies
    command: ./gradlew dependencies
  - &gradle-test
    name: Gradle Test
    command: ./gradlew test
  - &make-executable
    name: Make Jar Executable
    command: ./gradlew bootJar
  - &setup-remote-docker
    setup_remote_docker:
      docker_layer_caching: true
  - &update_submodules
    name: Update submodules
    command: |
      git submodule init && \
      git submodule update
  - &containerize-push
    name: Containerize and Push
    command: |
      echo $DOCKER_PASSWORD > docker_passwd && \
      docker login -u $DOCKER_USERNAME --password-stdin < docker_passwd && rm docker_passwd && \
      docker build -t aeternas/swadeshness-spring:$CIRCLE_BRANCH . && \
      docker push aeternas/swadeshness-spring:$CIRCLE_BRANCH
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: *update_submodules
      - restore_cache: *restore-cache
      - run: *gradle-deps
      - save_cache: *save-cache
      - run: *gradle-test
      - run: *make-executable
      - *setup-remote-docker
      - deploy: *containerize-push
